name: Run Crawler (debug production)

on:
  # Note:
  # テーブル行数0のエラーは手動実行だと再現しないため、一時的に自動で実行する。
  schedule:
    # 21時
    - cron: '0 12 1 * *'
  workflow_dispatch:
    inputs:
      months:
        type: choice
        description: How many months to go back
        options: 
        - 1
        - 2
        - 3

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.6.0'
      - name: Install Dependencies
        run: npm ci
      - name: Run Crawler
        run: npm run main:debug
        continue-on-error: true
        env:
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
          LOGIN_TOTP_SECRET: ${{ secrets.LOGIN_TOTP_SECRET }}
          INPUT_MONTHS: ${{ github.event.inputs.months }}
          LINE_MESSAGING_API_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_MESSAGING_API_CHANNEL_ACCESS_TOKEN }}
          # テスト用のLINEグループID
          LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID_DEBUG }}
      # note: GitHub Actions 上でスクリーンショットを取るための設定
      - name: Download screenshot
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshot
          path: tmp/
